project:
  title: "econometria-tp1"
  output-dir: docs  

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    # mainfont: Latin Modern Roman
    # sansfont: Latin Modern Roman
    
bibliography: biblio.bib
csl: apa7.csl
lang: es
editor: visual